#!/bin/bash

directory=`pwd`
result="$directory/.result.scraper"

curl -ski -L -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36' $1 --output $result

echo "[+] Results for $1"

echo -e "\n[*] Artifactory API Token: " ; grep -E -o '(?:\s|=|:|"|^)AKC[a-zA-Z0-9]{10,}' $result

echo -e "\n[*] Artifactory Password: " ; grep -E -o '(?:\s|=|:|"|^)AP[\dABCDEF][a-zA-Z0-9]{8,}' $result

echo -e "\n[*] Authorization Basic: " ; grep -E -o "basic [a-zA-Z0-9_\\-:\\.=]+" $result

echo -e "\n[*] Authorization Bearer: " ; grep -E -o 'bearer [a-zA-Z0-9_\\-\\.=]+' $result

echo -e "\n[*] AWS Client ID: " ; grep -E -o '(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}' $result

echo -e "\n[*] AWS MWS Key: " ; grep -E -o 'amzn\.mws\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' $result

echo -e "\n[*] AWS Secret Key: " ; grep -E -o "(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]" $result

echo -e "\n[*] Base32: " ; grep -E -o '(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}={6}|[A-Z2-7]{4}={4}|[A-Z2-7]{5}={3}|[A-Z2-7]{7}=)?' $result

echo -e "\n[*] Base64: " ; grep -E -o '(eyJ|YTo|Tzo|PD[89]|aHR0cHM6L|aHR0cDo|rO0)[a-zA-Z0-9+/]+={0,2}' $result

echo -e "\n[*] Basic Auth Credentials: " ; grep -E -o '(?<=:\/\/)[a-zA-Z0-9]+:[a-zA-Z0-9]+@[a-zA-Z0-9]+\.[a-zA-Z]+' $result

echo -e "\n[*] Cloudinary Basic Auth: " ; grep -E -o 'cloudinary:\/\/[0-9]{15}:[0-9A-Za-z]+@[a-z]+' $result

echo -e "\n[*] Facebook Access Token: " ; grep -E -o 'EAACEdEose0cBA[0-9A-Za-z]+' $result

echo -e "\n[*] Facebook Client ID: " ; grep -E -o "(?i)(facebook|fb)(.{0,20})?['\"][0-9]{13,17}" $result

echo -e "\n[*] Facebook Oauth: " ; grep -E -o "[f|F][a|A][c|C][e|E][b|B][o|O][o|O][k|K].*['|\"][0-9a-f]{32}['|\"]" $result

echo -e "\n[*] Facebook Secret Key: " ; grep -E -o "(?i)(facebook|fb)(.{0,20})?(?-i)['\"][0-9a-f]{32}" $result

echo -e "\n[*] Github: " ; grep -E -o "(?i)github(.{0,20})?(?-i)['\"][0-9a-zA-Z]{35,40}" $result

echo -e "\n[*] Google API Key: " ; grep -E -o "AIza[0-9A-Za-z\\-_]{35}" $result

echo -e "\n[*] Google Cloud Platform API Key: " ; grep -E -o "(?i)(google|gcp|youtube|drive|yt)(.{0,20})?['\"][AIza[0-9a-z\\-_]{35}]['\"]" $result

echo -e "\n[*] Google Drive API Key: " ; grep -E -o "AIza[0-9A-Za-z\\-_]{35}" $result

echo -e "\n[*] Google Drive Oauth: " ; grep -E -o "[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com" $result

echo -e "\n[*] Google Gmail API Key: " ; grep -E -o "AIza[0-9A-Za-z\\-_]{35}" $result

echo -e "\n[*] Google Gmail Oauth: " ; grep -E -o "[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com" $result

echo -e "\n[*] Google Oauth Access Token: " ; grep -E -o "ya29\\.[0-9A-Za-z\\-_]+" $result

echo -e "\n[*] Google Youtube API Key: " ; grep -E -o "AIza[0-9A-Za-z\\-_]{35}" $result

echo -e "\n[*] Google Youtube Oauth: " ; grep -E -o "[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\\.com" $result

echo -e "\n[*] Heroku API Key: " ; grep -E -o "[h|H][e|E][r|R][o|O][k|K][u|U].{0,30}[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}" $result

echo -e "\n[*] IPv4: " ; grep -E -o "\b(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}\b" $result

echo -e "\n[*] IPv6: " ; grep -E -o "(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))" $result

echo -e "\n[*] Javascript Variables: " ; grep -E -o "(?:const|let|var)\s+\K(\w+?)(?=[;.=\s])" $result

echo -e "\n[*] LinkedIn Client ID: " ; grep -E -o "(?i)linkedin(.{0,20})?(?-i)['\"][0-9a-z]{12}['\"]" $result

echo -e "\n[*] LinkedIn Secret Key: " ; grep -E -o "(?i)linkedin(.{0,20})?['\"][0-9a-z]{16}['\"]" $result

echo -e "\n[*] Mailchamp API Key: " ; grep -E -o "[0-9a-f]{32}-us[0-9]{1,2}" $result

echo -e "\n[*] Mailgun API Key: " ; grep -E -o "key-[0-9a-zA-Z]{32}" $result

echo -e "\n[*] MAilto: " ; grep -E -o "(?<=mailto:)[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9.-]+" $result

echo -e "\n[*] MD5 Hash: " ; grep -E -o "[a-f0-9]{32}" $result

echo -e "\n[*] Picatic API Key: " ; grep -E -o "sk_live_[0-9a-z]{32}" $result

echo -e "\n[*] Slack Token: " ; grep -E -o "xox[baprs]-([0-9a-zA-Z]{10,48})?" $result

echo -e "\n[*] Slack Webhook: " ; grep -E -o "https://hooks.slack.com/services/T[a-zA-Z0-9_]{10}/B[a-zA-Z0-9_]{10}/[a-zA-Z0-9_]{24}" $result

echo -e "\n[*] Stripe API Key: " ; grep -E -o "(?:r|s)k_live_[0-9a-zA-Z]{24}" $result

echo -e "\n[*] Square Access Token: " ; grep -E -o "sqOatp-[0-9A-Za-z\\-_]{22}" $result

echo -e "\n[*] Square Oauth Secret: " ; grep -E -o "sq0csp-[ 0-9A-Za-z\\-_]{43}" $result

echo -e "\n[*] Twilio API Key: " ; grep -E -o "SK[0-9a-fA-F]{32}" $result

echo -e "\n[*] Twitter Client ID: " ; grep -E -o "(?i)twitter(.{0,20})?['\"][0-9a-z]{18,25}" $result

echo -e "\n[*] Twitter Oauth: " ; grep -E -o "[t|T][w|W][i|I][t|T][t|T][e|E][r|R].{0,30}['\"\\s][0-9a-zA-Z]{35,44}['\"\\s]" $result

echo -e "\n[*] Twitter Secret Key: " ; grep -E -o "(?i)twitter(.{0,20})?['\"][0-9a-z]{35,44}" $result

echo -e "\n[*] Vault Token: " ; grep -E -o "[sb]\.[a-zA-Z0-9]{24}" $result

echo -e "\n[*] URL Parameter: " ; grep -E -o '(?<=\?|\&)[a-zA-Z0-9_]+(?=\=)' $result

echo -e "\n[*] URLs with HTTP: " ; grep -E -o 'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)' $result

echo -e "\n[*] URLs without protocol: " ; grep -E -o '[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)' $result

echo -e "\n[!] Cleaning ..."
rm $result
