#!/bin/bash

directory=`pwd`
result="$directory/.result.scraper"

curl -ski -L -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36' $1 --output $result

echo "Artifactory API Token: " ; grep -E -o '(?:\s|=|:|"|^)AKC[a-zA-Z0-9]{10,}' $result

echo -e "\nArtifactory Password: " ; grep -E -o '(?:\s|=|:|"|^)AP[\dABCDEF][a-zA-Z0-9]{8,}' $result

echo -e "\nAuthorization Basic: " ; grep -E -o "basic [a-zA-Z0-9_\\-:\\.=]+" $result

echo -e "\nAuthorization Bearer: " ; grep -E -o 'bearer [a-zA-Z0-9_\\-\\.=]+' $result

echo -e "\nAWS Client ID: " ; grep -E -o '(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}' $result

echo -e "\nAWS MWS Key: " ; grep -E -o 'amzn\.mws\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' $result

echo -e "\nAWS Secret Key: " ; grep -E -o "(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]" $result

echo -e "\nBase32: " ; grep -E -o '(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}={6}|[A-Z2-7]{4}={4}|[A-Z2-7]{5}={3}|[A-Z2-7]{7}=)?' $result

echo -e "\nBase64: " ; grep -E -o '(eyJ|YTo|Tzo|PD[89]|aHR0cHM6L|aHR0cDo|rO0)[a-zA-Z0-9+/]+={0,2}' $result

echo -e "\nBasic Auth Credentials: " ; grep -E -o '(?<=:\/\/)[a-zA-Z0-9]+:[a-zA-Z0-9]+@[a-zA-Z0-9]+\.[a-zA-Z]+' $result

echo -e "\nCloudinary Basic Auth: " ; grep -E -o 'cloudinary:\/\/[0-9]{15}:[0-9A-Za-z]+@[a-z]+' $result

echo -e "\nFacebook Access Token: " ; grep -E -o 'EAACEdEose0cBA[0-9A-Za-z]+' $result

echo -e "\nFacebook Client ID: " ; grep -E -o "(?i)(facebook|fb)(.{0,20})?['\"][0-9]{13,17}" $result

echo -e "\nFacebook Oauth: " ; grep -E -o "[f|F][a|A][c|C][e|E][b|B][o|O][o|O][k|K].*['|\"][0-9a-f]{32}['|\"]" $result

echo -e "\nFacebook Secret Key: " ; grep -E -o "(?i)(facebook|fb)(.{0,20})?(?-i)['\"][0-9a-f]{32}" $result

echo -e "\nGithub: " ; grep -E -o "(?i)github(.{0,20})?(?-i)['\"][0-9a-zA-Z]{35,40}" $result

echo -e "\nGoogle API Key: " ; grep -E -o "AIza[0-9A-Za-z\\-_]{35}" $result

echo -e "\nGoogle Cloud Platform API Key: " ; grep -E -o "(?i)(google|gcp|youtube|drive|yt)(.{0,20})?['\"][AIza[0-9a-z\\-_]{35}]['\"]" $result

echo -e "\nGoogle Drive API Key: " ; grep -E -o "AIza[0-9A-Za-z\\-_]{35}" $result

echo -e "\nGoogle Drive Oauth: " ; grep -E -o "[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com" $result

echo -e "\nGoogle Gmail API Key: " ; grep -E -o "AIza[0-9A-Za-z\\-_]{35}" $result

echo -e "\nGoogle Gmail Oauth: " ; grep -E -o "[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com" $result

echo -e "\nGoogle Oauth Access Token: " ; grep -E -o "ya29\\.[0-9A-Za-z\\-_]+" $result

echo -e "\nGoogle Youtube API Key: " ; grep -E -o "AIza[0-9A-Za-z\\-_]{35}" $result

echo -e "\nGoogle Youtube Oauth: " ; grep -E -o "[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\\.com" $result

echo -e "\nHeroku API Key: " ; grep -E -o "[h|H][e|E][r|R][o|O][k|K][u|U].{0,30}[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}" $result

echo -e "\nIPv4: " ; grep -E -o "\b(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}\b" $result

echo -e "\nIPv6: " ; grep -E -o "(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))" $result

echo -e "\nJavascript Variables: " ; grep -E -o "(?:const|let|var)\s+\K(\w+?)(?=[;.=\s])" $result

echo -e "\nLinkedIn Client ID: " ; grep -E -o "(?i)linkedin(.{0,20})?(?-i)['\"][0-9a-z]{12}['\"]" $result

echo -e "\nLinkedIn Secret Key: " ; grep -E -o "(?i)linkedin(.{0,20})?['\"][0-9a-z]{16}['\"]" $result

echo -e "\nMailchamp API Key: " ; grep -E -o "[0-9a-f]{32}-us[0-9]{1,2}" $result

echo -e "\nMailgun API Key: " ; grep -E -o "key-[0-9a-zA-Z]{32}" $result

echo -e "\nMAilto: " ; grep -E -o "(?<=mailto:)[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9.-]+" $result

echo -e "\nMD5 Hash: " ; grep -E -o "[a-f0-9]{32}" $result

echo -e "\nPicatic API Key: " ; grep -E -o "sk_live_[0-9a-z]{32}" $result

echo -e "\nSlack Token: " ; grep -E -o "xox[baprs]-([0-9a-zA-Z]{10,48})?" $result

echo -e "\nSlack Webhook: " ; grep -E -o "https://hooks.slack.com/services/T[a-zA-Z0-9_]{10}/B[a-zA-Z0-9_]{10}/[a-zA-Z0-9_]{24}" $result

echo -e "\nStripe API Key: " ; grep -E -o "(?:r|s)k_live_[0-9a-zA-Z]{24}" $result

echo -e "\nSquare Access Token: " ; grep -E -o "sqOatp-[0-9A-Za-z\\-_]{22}" $result

echo -e "\nSquare Oauth Secret: " ; grep -E -o "sq0csp-[ 0-9A-Za-z\\-_]{43}" $result

echo -e "\nTwilio API Key: " ; grep -E -o "SK[0-9a-fA-F]{32}" $result

echo -e "\nTwitter Client ID: " ; grep -E -o "(?i)twitter(.{0,20})?['\"][0-9a-z]{18,25}" $result

echo -e "\nTwitter Oauth: " ; grep -E -o "[t|T][w|W][i|I][t|T][t|T][e|E][r|R].{0,30}['\"\\s][0-9a-zA-Z]{35,44}['\"\\s]" $result

echo -e "\nTwitter Secret Key: " ; grep -E -o "(?i)twitter(.{0,20})?['\"][0-9a-z]{35,44}" $result

echo -e "\nVault Token: " ; grep -E -o "[sb]\.[a-zA-Z0-9]{24}" $result

echo -e "\nURL Parameter: " ; grep -E -o '(?<=\?|\&)[a-zA-Z0-9_]+(?=\=)' $result

echo -e "\nURLs with HTTP: " ; grep -E -o 'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)' $result

echo -e "\nURLs without protocol: " ; grep -E -o '[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)' $result

echo -e "\nCleaning ..."
rm $result
